### ISSUE TITLE
"No config for build app; found" (yarn run script error)

### ISSUE THREAD

**Issue by mjmlvp** [jacekschae/shadow-re-frame#3]
Hi, thanks for a great starting point for development.

My issue seems to be the same one as robjens had on the the conduit app. See: https://github.com/jacekschae/conduit/issues/5

Again, semicolons are giving problems: If I remove the semicolons from package.json, then running e.g. 'yarn dev' runs fine on the windows command line.

**Comment by jacekschae** [comment]
Glat to hear that you find it useful. 

Thanks for reporting. This should be fixed in this repo, also I bumped deps. 

I should convert all my repos and remove the ";".
